sub_species={
            'totRac':['pKalRac','RacGap','RacGDP','RacGTP','RacPAK','RacPAKLIMK','RacPAKSSH','RCapGDP'],
            'totPAK':['PAK','RacPAK','RacPAKLIMK','RacPAKSSH'],
            'totCof':['Cof','Cofactin','pCof','pLIMKCof','SSHpCof'],
            'PKA':['PKA','PKAcAMP2','PKAcAMP4'],
            'CKtot':['KalCKCamCa4','KalCKpCamCa4','CKp','CKCamCa4','CKpCamCa4','CKpPP1','CKpCamCa4PP1'],
            'LIMKtot':['RacPAKLIMK','LIMK','pLIMK','pLIMKCof','SSHpLIMK'],
            'ssh':['CaNCamCa4pSSH','pSSH','SSH','SSHpLIMK','SSHpCof','RacPAKSSH','SCappSSH'],
            'Kal':['Kal','KalCKCamCa4','KalCKpCamCa4','pKal','pKalPP1','pKalRac'],
            'Gs':['GsR', 'LRGs','Gs', 'Gsbg',"AC1GasGTP","AC1GasGTPCamCa4","AC1GasGTPCamCa4ATP"],
            'R':['R','LR','GsR','LRGs','pLR'],
            'AC1':["AC1","AC1CamCa4","AC1CamCa4ATP","AC1GasGTP","AC1GasGTPCamCa4","AC1GasGTPCamCa4ATP"],
            'AC8':["AC8","AC8CamCa4","AC8CamCa4ATP"],
            'PP1':['PP1','Ip35PP1', 'pKalPP1','CKpPP1','CKpCamCa4PP1'],
            'I1':['Ip35','Ip35PP1','Ip35CaNCamCa4','Ip35PP1CaNCamCa4','I1'],
            'Gap':['Gap','RacGAP'],
            'CaN':['CaN','CaNCam','CaNCamCa2C','CaNCamCa2N','CaNCamCa4','CaNCamCa4pSSH'],
            'PDE4':['PDE4','PDE4cAMP','pPDE4','pPDE4cAMP','PKAc_PDE4_cAMP','PKAcPDE4'],
            'PDE1':['PDE1','PDE1CamCa4','PDE1CamCa4cAMP'],
            'Epac':['Epac','EpacAMP'],
            'Calbin':['Calbin','CalbinC'],
            'Ng':['Ng','NgCam'],
            }
